//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileExplorer.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileExplorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ....
        /// </summary>
        public static string buttonText {
            get {
                return ResourceManager.GetString("buttonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File Explorer.
        /// </summary>
        public static string fileExplorer {
            get {
                return ResourceManager.GetString("fileExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Files:.
        /// </summary>
        public static string files {
            get {
                return ResourceManager.GetString("files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Folders:.
        /// </summary>
        public static string folders {
            get {
                return ResourceManager.GetString("folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Directory has been parsed successfully..
        /// </summary>
        public static string parseSuccess {
            get {
                return ResourceManager.GetString("parseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parsing directory...
        /// </summary>
        public static string parsingDirectory {
            get {
                return ResourceManager.GetString("parsingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Size of Selected Files(bytes):.
        /// </summary>
        public static string selectedBytes {
            get {
                return ResourceManager.GetString("selectedBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selected Files:.
        /// </summary>
        public static string selectedFiles {
            get {
                return ResourceManager.GetString("selectedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selected Folders:.
        /// </summary>
        public static string selectedFolders {
            get {
                return ResourceManager.GetString("selectedFolders", resourceCulture);
            }
        }
    }
}
